services:
  db:
    image: mysql:8.0
    container_name: mysql-gestion
    environment:
      MYSQL_ROOT_PASSWORD: root_pass123     # contrase침a de root
      MYSQL_DATABASE: gestion_empresa      # base de datos que se crear치
      MYSQL_USER: gestion_user             # usuario no-root
      MYSQL_PASSWORD: gestion_pass123      # contrase침a de ese usuario
    ports:
      - "3307:3306"                      # mapeo de puerto para acceder desde tu host
    volumes:
      - mysql_data:/var/lib/mysql          # volumen persistente
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - gestion-network
  
  api:
    build:
      context: ./api_django
      dockerfile: Dockerfile
    container_name: api-gestion
    volumes:
      - ./api_django:/app         # hot reload: cualquier cambio en el c칩digo se refleja inmediatamente
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_HOST=db
      - DATABASE_NAME=gestion_empresa
      - DATABASE_USER=gestion_user
      - DATABASE_PASSWORD=gestion_pass123
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - gestion-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-gestion
    volumes:
      - ./frontend:/app           # hot reload: cambios en tiempo real
      - /app/.next                # cache de Next.js
    ports:
      - "3000:3000"               # puerto para acceder al frontend
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    restart: unless-stopped
    networks:
      - gestion-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_pass123
      MYSQL_DATABASE: gestion_empresa
      MYSQL_USER: gestion_user
      MYSQL_PASSWORD: gestion_pass123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - gestion-network

volumes:
  mysql_data:

networks:
  gestion-network:
    driver: bridge
