# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_factura_pedido_pedido_entregado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albaran',
            table=None,
        ),
        migrations.AlterModelTable(
            name='albaranitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='factura',
            table=None,
        ),
        migrations.AlterModelTable(
            name='facturaitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedidoitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='presupuesto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='presupuestoitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketitem',
            table=None,
        ),
    ]
