# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
