# Generated by Django 5.2.3 on 2025-06-26 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del invitado')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador de Empresa'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('readonly', 'Solo Lectura')], default='employee', max_length=20, verbose_name='Rol asignado')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token de invitación')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Puede gestionar usuarios')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Puede ver reportes')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Puede gestionar configuración')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Mensaje personalizado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='accounts.empresa', verbose_name='Empresa')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
            ],
            options={
                'verbose_name': 'Invitación de Usuario',
                'verbose_name_plural': 'Invitaciones de Usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_us_token_15d7e5_idx'), models.Index(fields=['email'], name='accounts_us_email_d01203_idx'), models.Index(fields=['status'], name='accounts_us_status_bb7459_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_41fb24_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email', 'empresa', 'status'), name='unique_pending_invitation_per_email_empresa')],
            },
        ),
    ]
