# Generated by Django 5.2.3 on 2025-07-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID del documento')),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF almacenado en S3', upload_to='pdfs/%Y/%m/')),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo PDF', max_length=255)),
                ('hash_documento', models.CharField(db_index=True, help_text='SHA256 hash del contenido del documento para evitar duplicados', max_length=64)),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del PDF (por si el documento cambia)')),
                ('enviado_por_email', models.BooleanField(default=False, help_text='Indica si este PDF ha sido enviado por email')),
                ('fecha_ultimo_envio', models.DateTimeField(blank=True, help_text='Fecha del último envío por email', null=True)),
                ('email_destinatario', models.EmailField(blank=True, help_text='Último email destinatario', max_length=254)),
                ('contador_envios', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha enviado este PDF')),
                ('tamaño_archivo', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de documento (Factura, Presupuesto, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'PDF de Documento',
                'verbose_name_plural': 'PDFs de Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'content_type', 'object_id'], name='documents_d_empresa_286e95_idx'), models.Index(fields=['hash_documento'], name='documents_d_hash_do_4fac01_idx'), models.Index(fields=['created_at'], name='documents_d_created_664a3b_idx')],
                'unique_together': {('empresa', 'content_type', 'object_id', 'hash_documento')},
            },
        ),
    ]
