# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_empleado_fecha_contratacion_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='empleado',
            table=None,
        ),
    ]
