# Generated by Django 5.2.3 on 2025-07-23 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_departamento_empresa_empleado_empresa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empleado",
            options={
                "ordering": ["usuario__last_name", "usuario__first_name"],
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
        migrations.AlterUniqueTogether(
            name="empleado",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="empleado",
            name="numero_empleado",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número de empleado"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuario del sistema asociado a este empleado",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_empleado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Empleado activo"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.departamento",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="fecha_contratacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de contratación"
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="puesto",
            field=models.CharField(
                blank=True,
                help_text="Cargo específico del empleado (puede diferir del campo 'cargo' del usuario)",
                max_length=100,
                null=True,
                verbose_name="Puesto de trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="salario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Salario mensual",
            ),
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="email",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="telefono",
        ),
    ]
