# Generated by Django 5.2.3 on 2025-06-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('PERMISSION_DENIED', 'Acceso Denegado'), ('BUSINESS_ACTION', 'Acción de Negocio')], db_index=True, max_length=20)),
                ('level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], db_index=True, default='MEDIUM', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Valores anteriores', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Valores nuevos', null=True)),
                ('changes', models.JSONField(blank=True, help_text='Solo campos modificados', null=True)),
                ('description', models.TextField(help_text='Descripción del evento')),
                ('module', models.CharField(db_index=True, help_text='Módulo/App donde ocurrió', max_length=50)),
                ('business_context', models.JSONField(blank=True, help_text='Contexto de negocio', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa', 'timestamp'], name='audit_audit_empresa_f60502_idx'), models.Index(fields=['empresa', 'user', 'timestamp'], name='audit_audit_empresa_fa1b0d_idx'), models.Index(fields=['empresa', 'table_name', 'timestamp'], name='audit_audit_empresa_ed230d_idx'), models.Index(fields=['empresa', 'action', 'level'], name='audit_audit_empresa_9f7bc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('SALE_CREATED', 'Venta Creada'), ('INVOICE_GENERATED', 'Factura Generada'), ('STOCK_UPDATED', 'Stock Actualizado'), ('STOCK_LOW', 'Stock Bajo'), ('PAYMENT_RECEIVED', 'Pago Recibido'), ('DOCUMENT_CONVERTED', 'Documento Convertido'), ('BACKUP_CREATED', 'Backup Creado'), ('REPORT_GENERATED', 'Reporte Generado')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('data', models.JSONField(help_text='Datos específicos del evento')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Evento de Negocio',
                'verbose_name_plural': 'Logs de Eventos de Negocio',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa', 'timestamp'], name='audit_busin_empresa_a4f479_idx'), models.Index(fields=['empresa', 'event'], name='audit_busin_empresa_8522e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('response_time', models.FloatField(help_text='Tiempo en segundos')),
                ('db_queries_count', models.PositiveIntegerField(default=0)),
                ('db_time', models.FloatField(default=0.0, help_text='Tiempo DB en segundos')),
                ('memory_usage', models.FloatField(blank=True, help_text='MB', null=True)),
                ('is_slow', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Performance',
                'verbose_name_plural': 'Logs de Performance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa', 'timestamp'], name='audit_perfo_empresa_9d38c0_idx'), models.Index(fields=['empresa', 'is_slow'], name='audit_perfo_empresa_1fd274_idx'), models.Index(fields=['path', 'timestamp'], name='audit_perfo_path_93c28d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Exitoso'), ('LOGIN_FAILED', 'Login Fallido'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Cambio Contraseña'), ('PERMISSION_DENIED', 'Permiso Denegado'), ('SUSPICIOUS_ACTIVITY', 'Actividad Sospechosa'), ('RATE_LIMIT_EXCEEDED', 'Límite de Requests Excedido'), ('TOKEN_REFRESH', 'Renovación Token'), ('TOKEN_INVALID', 'Token Inválido')], db_index=True, max_length=30)),
                ('username_attempted', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', max_length=10)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Seguridad',
                'verbose_name_plural': 'Logs de Seguridad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa', 'timestamp'], name='audit_secur_empresa_c230d3_idx'), models.Index(fields=['empresa', 'event', 'success'], name='audit_secur_empresa_c6e2dd_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_secur_ip_addr_c350bb_idx')],
            },
        ),
    ]
