# Generated by Django 5.2.3 on 2025-06-30 11:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('core', '0006_serie'),
        ('inventory', '0001_initial'),
        ('products', '0004_articulo_empresa_categoria_empresa_marca_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbaranCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido_parcial', 'Recibido Parcial'), ('recibido_total', 'Recibido Total'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('numero_albaran_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número albarán proveedor')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='Almacén')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Albarán de Compra',
                'verbose_name_plural': 'Albaranes de Compra',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='AlbaranCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento %')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA %')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad recibida')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.albarancompra', verbose_name='Albarán')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Item de Albarán de Compra',
                'verbose_name_plural': 'Items de Albarán de Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('numero_factura_proveedor', models.CharField(max_length=50, verbose_name='Número factura proveedor')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de pago')),
                ('albaran_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='purchases.albarancompra', verbose_name='Albarán de compra')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto original')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto pagado')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pendiente')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_parcial', 'Pagado Parcial'), ('pagado_total', 'Pagado Total'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
                ('factura_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='purchases.facturacompra', verbose_name='Factura de compra')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('recibido_parcial', 'Recibido Parcial'), ('recibido_total', 'Recibido Total'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de entrega')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de pago')),
                ('referencia_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia del proveedor')),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='Almacén destino')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='purchases.pedidocompra', verbose_name='Pedido de compra'),
        ),
        migrations.AddField(
            model_name='albarancompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albaranes', to='purchases.pedidocompra', verbose_name='Pedido de compra'),
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento %')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA %')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad recibida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.pedidocompra', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Compra',
                'verbose_name_plural': 'Items de Pedido de Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento %')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA %')),
                ('albaran_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.albarancompraitem', verbose_name='Item del albarán')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.facturacompra', verbose_name='Factura')),
                ('pedido_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.pedidocompraitem', verbose_name='Item del pedido')),
            ],
            options={
                'verbose_name': 'Item de Factura de Compra',
                'verbose_name_plural': 'Items de Factura de Compra',
            },
        ),
        migrations.AddField(
            model_name='albarancompraitem',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.pedidocompraitem', verbose_name='Item del pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='albarancompra',
            unique_together={('empresa', 'numero')},
        ),
    ]
