# Generated by Django 5.2.3 on 2025-06-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0003_alter_albaran_table_alter_albaranitem_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albaran',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='documento_origen',
            field=models.CharField(blank=True, help_text='Tipo de documento del que se genera esta factura', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='albaran',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('empresa', 'numero')},
        ),
    ]
