# Generated by Django 5.2.3 on 2025-06-27 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serie'),
        ('sales', '0004_albaran_empresa_factura_empresa_pedido_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie asociada al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serie'),
        ),
        migrations.AddField(
            model_name='factura',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie asociada al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serie'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie asociada al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serie'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie asociada al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie asociada al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serie'),
        ),
    ]
