# Generated by Django 5.2.3 on 2025-07-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_factura_albaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='presupuesto',
            field=models.ForeignKey(blank=True, help_text='Presupuesto del que se genera esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='sales.presupuesto'),
        ),
    ]
