# Generated by Django 5.2.3 on 2025-06-27 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0004_articulo_empresa_categoria_empresa_marca_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del almacén')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código del almacén')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Población')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es almacén principal')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia_salida', 'Transferencia (Salida)'), ('transferencia_entrada', 'Transferencia (Entrada)'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('inicial', 'Stock Inicial')], help_text='Tipo de movimiento', max_length=25)),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('devolucion_cliente', 'Devolución de Cliente'), ('devolucion_proveedor', 'Devolución a Proveedor'), ('transferencia', 'Transferencia entre Almacenes'), ('ajuste_inventario', 'Ajuste de Inventario'), ('rotura', 'Rotura/Pérdida'), ('caducidad', 'Caducidad'), ('inicial', 'Stock Inicial'), ('otros', 'Otros')], max_length=30, verbose_name='Motivo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.PositiveIntegerField(verbose_name='Stock posterior')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='Almacén')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='inventory.almacen', verbose_name='Almacén destino')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de transferencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(verbose_name='Motivo de la transferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='inventory.almacen', verbose_name='Almacén destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='inventory.almacen', verbose_name='Almacén origen')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Transferencia de stock',
                'verbose_name_plural': 'Transferencias de stock',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ArticuloStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('stock_maximo', models.PositiveIntegerField(default=0, verbose_name='Stock máximo')),
                ('stock_reservado', models.PositiveIntegerField(default=0, verbose_name='Stock reservado')),
                ('pasillo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pasillo')),
                ('estanteria', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estantería')),
                ('nivel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='Almacén')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Stock de artículo',
                'verbose_name_plural': 'Stock de artículos',
                'ordering': ['almacen__nombre', 'articulo__nombre'],
                'unique_together': {('empresa', 'articulo', 'almacen')},
            },
        ),
        migrations.CreateModel(
            name='TransferenciaStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad solicitada')),
                ('cantidad_enviada', models.PositiveIntegerField(default=0, verbose_name='Cantidad enviada')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad recibida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferenciastock', verbose_name='Transferencia')),
            ],
            options={
                'verbose_name': 'Item de transferencia',
                'verbose_name_plural': 'Items de transferencia',
                'ordering': ['articulo__nombre'],
                'unique_together': {('empresa', 'transferencia', 'articulo')},
            },
        ),
    ]
