# Generated by Django 5.2.3 on 2025-06-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_alter_articulo_table_alter_categoria_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('empresa', 'nombre')},
        ),
    ]
