# Generated by Django 5.2.3 on 2025-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_empresa',
            field=models.BooleanField(default=True, verbose_name='Es empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='identificacion_vat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificación VAT'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='España', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.CharField(blank=True, help_text='Separar por comas', max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_empresa',
            field=models.BooleanField(default=True, verbose_name='Es empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='identificacion_vat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificación VAT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='España', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tags',
            field=models.CharField(blank=True, help_text='Separar por comas', max_length=500, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
    ]
