# Generated by Django 5.2.3 on 2025-06-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('core', '0005_alter_cliente_options_alter_proveedor_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Serie activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='Almacén asociado')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
