# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_empleados'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table=None,
        ),
    ]
