# Generated by Django 5.2.3 on 2025-06-26 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0004_albaran_empresa_factura_empresa_pedido_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Principal, Caja 1, etc.', max_length=100, verbose_name='Nombre de la caja')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('suspendida', 'Suspendida')], default='abierta', max_length=20, verbose_name='Estado')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, help_text='Dinero en efectivo al abrir la caja', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo inicial')),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo final')),
                ('notas_apertura', models.TextField(blank=True, null=True, verbose_name='Notas de apertura')),
                ('notas_cierre', models.TextField(blank=True, null=True, verbose_name='Notas de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CuadreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo_contado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo contado físicamente')),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo esperado según sistema')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diferencia (contado - esperado)')),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas en efectivo')),
                ('total_ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas con tarjeta')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas del día')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuadre', to='pos.cajasession', verbose_name='Sesión de caja')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuadre de Caja',
                'verbose_name_plural': 'Cuadres de Caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('devolucion', 'Devolución'), ('entrada', 'Entrada de dinero'), ('salida', 'Salida de dinero')], max_length=20, verbose_name='Tipo de movimiento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Pago mixto')], max_length=20, verbose_name='Método de pago')),
                ('importe_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe en efectivo')),
                ('importe_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe con tarjeta')),
                ('concepto', models.CharField(blank=True, help_text='Descripción del movimiento', max_length=200, null=True, verbose_name='Concepto')),
                ('referencia', models.CharField(blank=True, help_text='Número de autorización, referencia bancaria, etc.', max_length=100, null=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caja_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pos.cajasession', verbose_name='Sesión de caja')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='Empresa')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.ticket', verbose_name='Ticket asociado')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
