# Generated by Django 5.2.3 on 2025-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_empleado_fecha_contratacion_empleado_puesto_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='hr.empleado'),
        ),
    ]
