# Generated by Django 5.2.3 on 2025-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_factura_pedido_albaran_factura_albaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
    ]
