# Generated by Django 5.2.3 on 2025-06-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_articulo_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='albaran',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='albaranitem',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
    ]
