# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_articulo_iva_articulo_modelo_marca_pais_origen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articulo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marca',
            table=None,
        ),
    ]
